const fs = require('fs');

// Write product_detail_screen.dart
// Using string concatenation to avoid template literal interpolation issues
const S = '$';

const dart = [
  "import 'package:flutter/material.dart';",
  "import 'package:flutter_riverpod/flutter_riverpod.dart';",
  "import 'package:go_router/go_router.dart';",
  "import '../../shared/theme/app_theme.dart';",
  "import '../../core/services/api_service.dart';",
  "import '../../core/providers/auth_provider.dart';",
  "",
  "class ProductDetailScreen extends ConsumerStatefulWidget {",
  "  final String productId;",
  "  const ProductDetailScreen({super.key, required this.productId});",
  "  @override",
  "  ConsumerState<ProductDetailScreen> createState() => _ProductDetailScreenState();",
  "}",
  "",
  "class _ProductDetailScreenState extends ConsumerState<ProductDetailScreen> {",
  "  Map<String, dynamic>? _product;",
  "  bool _loading = true;",
  "  String? _error;",
  "",
  "  @override",
  "  void initState() { super.initState(); _loadProduct(); }",
  "",
  "  Future<void> _loadProduct() async {",
  "    try {",
  "      final api = ref.read(apiServiceProvider);",
  "      final res = await api.get('/products/" + S + "{widget.productId}');",
  "      setState(() { _product = Map<String, dynamic>.from(res.data as Map); _loading = false; });",
  "    } catch (e) {",
  "      setState(() { _error = e.toString(); _loading = false; });",
  "    }",
  "  }",
  "",
  "  @override",
  "  Widget build(BuildContext context) {",
  "    final auth = ref.watch(authStateProvider);",
  "    final isBuyer = auth.role != 'artisan';",
  "",
  "    if (_loading) return const Scaffold(body: Center(child: CircularProgressIndicator(color: AppTheme.primary)));",
  "    if (_error != null || _product == null) return Scaffold(",
  "      appBar: AppBar(title: const Text('Product')),",
  "      body: Center(child: Text(_error ?? 'Product not found')),",
  "    );",
  "",
  "    final p = _product!;",
  "    final title = p['title'] as String? ?? 'Untitled';",
  "    final description = p['description'] as String? ?? '';",
  "    final category = p['category'] as String? ?? '';",
  "    final material = p['material'] as String? ?? '';",
  "    final craft = p['craft'] as String? ?? '';",
  "    final region = p['region'] as String? ?? '';",
  "    final priceMin = (p['priceMin'] as num?)?.toDouble();",
  "    final priceMax = (p['priceMax'] as num?)?.toDouble();",
  "    final tags = (p['tags'] as List?)?.cast<String>() ?? [];",
  "",
  "    return Scaffold(",
  "      appBar: AppBar(title: Text(title, overflow: TextOverflow.ellipsis)),",
  "      body: SingleChildScrollView(",
  "        child: Column(",
  "          crossAxisAlignment: CrossAxisAlignment.start,",
  "          children: [",
  "            Container(",
  "              width: double.infinity, height: 280,",
  "              color: AppTheme.primary.withOpacity(0.08),",
  "              child: const Center(child: Icon(Icons.image_outlined, size: 80, color: AppTheme.primary)),",
  "            ),",
  "            Padding(",
  "              padding: const EdgeInsets.all(AppTheme.paddingLG),",
  "              child: Column(",
  "                crossAxisAlignment: CrossAxisAlignment.start,",
  "                children: [",
  "                  if (priceMin != null && priceMax != null)",
  "                    Container(",
  "                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),",
  "                      decoration: BoxDecoration(",
  "                        color: AppTheme.secondary.withOpacity(0.1),",
  "                        borderRadius: BorderRadius.circular(8),",
  "                      ),",
  "                      child: Text(",
  "                        'INR " + S + "{priceMin.toStringAsFixed(0)} - " + S + "{priceMax.toStringAsFixed(0)}',",
  "                        style: AppTheme.h3.copyWith(color: AppTheme.secondary),",
  "                      ),",
  "                    ),",
  "                  const SizedBox(height: 16),",
  "                  Text(title, style: AppTheme.h2),",
  "                  const SizedBox(height: 8),",
  "                  if (category.isNotEmpty) _Attribute(label: 'Category', value: category),",
  "                  if (material.isNotEmpty) _Attribute(label: 'Material', value: material),",
  "                  if (craft.isNotEmpty) _Attribute(label: 'Craft', value: craft),",
  "                  if (region.isNotEmpty) _Attribute(label: 'Region', value: region),",
  "                  const SizedBox(height: 16),",
  "                  if (description.isNotEmpty) ...[",
  "                    Text('About this Product', style: AppTheme.h3),",
  "                    const SizedBox(height: 8),",
  "                    Text(description, style: AppTheme.body.copyWith(color: AppTheme.textSecondary)),",
  "                    const SizedBox(height: 16),",
  "                  ],",
  "                  if (tags.isNotEmpty) ...[",
  "                    Wrap(",
  "                      spacing: 8, runSpacing: 8,",
  "                      children: tags.map((t) => Chip(",
  "                        label: Text(t),",
  "                        backgroundColor: AppTheme.primary.withOpacity(0.08),",
  "                        labelStyle: AppTheme.caption.copyWith(color: AppTheme.primary),",
  "                      )).toList(),",
  "                    ),",
  "                    const SizedBox(height: 24),",
  "                  ],",
  "                  if (isBuyer)",
  "                    ElevatedButton.icon(",
  "                      icon: const Icon(Icons.mail_outline),",
  "                      label: const Text('Send Inquiry to Artisan'),",
  "                      onPressed: () => context.push(",
  "                        '/inquiry/" + S + "{widget.productId}',",
  "                        extra: title,",
  "                      ),",
  "                    )",
  "                  else",
  "                    Container(",
  "                      padding: const EdgeInsets.all(12),",
  "                      decoration: BoxDecoration(",
  "                        color: AppTheme.primary.withOpacity(0.05),",
  "                        borderRadius: BorderRadius.circular(12),",
  "                        border: Border.all(color: AppTheme.borderLight),",
  "                      ),",
  "                      child: Row(children: [",
  "                        const Icon(Icons.storefront_outlined, color: AppTheme.primary),",
  "                        const SizedBox(width: 8),",
  "                        Text('This is your listing', style: AppTheme.bodySmall.copyWith(color: AppTheme.textSecondary)),",
  "                      ]),",
  "                    ),",
  "                ],",
  "              ),",
  "            ),",
  "          ],",
  "        ),",
  "      ),",
  "    );",
  "  }",
  "}",
  "",
  "class _Attribute extends StatelessWidget {",
  "  final String label, value;",
  "  const _Attribute({required this.label, required this.value});",
  "",
  "  @override",
  "  Widget build(BuildContext context) => Padding(",
  "        padding: const EdgeInsets.only(bottom: 6),",
  "        child: Row(",
  "          children: [",
  "            SizedBox(",
  "              width: 80,",
  "              child: Text(label, style: AppTheme.caption.copyWith(fontWeight: FontWeight.w600)),",
  "            ),",
  "            Expanded(child: Text(value, style: AppTheme.bodySmall)),",
  "          ],",
  "        ),",
  "      );",
  "}",
].join('\n');

fs.writeFileSync(
  'd:/Hacknex/mobile/lib/features/marketplace/product_detail_screen.dart',
  dart,
  { encoding: 'utf8' }
);
console.log('product_detail_screen.dart written, size:', dart.length);
