const fs = require('fs');
const S = '$';

const dart = [
  "import 'package:flutter/material.dart';",
  "import 'package:flutter_riverpod/flutter_riverpod.dart';",
  "import 'package:go_router/go_router.dart';",
  "import '../../shared/theme/app_theme.dart';",
  "import '../../core/services/api_service.dart';",
  "",
  "/// Buyer sends an inquiry to the artisan about a specific product.",
  "class InquiryScreen extends ConsumerStatefulWidget {",
  "  final String productId;",
  "  final String? productTitle;",
  "  const InquiryScreen({super.key, required this.productId, this.productTitle});",
  "",
  "  @override",
  "  ConsumerState<InquiryScreen> createState() => _InquiryScreenState();",
  "}",
  "",
  "class _InquiryScreenState extends ConsumerState<InquiryScreen> {",
  "  final _messageCtrl = TextEditingController();",
  "  bool _sending = false;",
  "  bool _sent = false;",
  "  String? _error;",
  "",
  "  @override",
  "  void dispose() {",
  "    _messageCtrl.dispose();",
  "    super.dispose();",
  "  }",
  "",
  "  Future<void> _sendInquiry() async {",
  "    final msg = _messageCtrl.text.trim();",
  "    if (msg.length < 10) {",
  "      setState(() => _error = 'Message must be at least 10 characters.');",
  "      return;",
  "    }",
  "    setState(() { _sending = true; _error = null; });",
  "    try {",
  "      final api = ref.read(apiServiceProvider);",
  "      await api.post('/inquiries', data: {",
  "        'productId': widget.productId,",
  "        'message': msg,",
  "      });",
  "      setState(() { _sent = true; _sending = false; });",
  "    } catch (e) {",
  "      setState(() { _error = 'Failed to send inquiry: " + S + "e'; _sending = false; });",
  "    }",
  "  }",
  "",
  "  @override",
  "  Widget build(BuildContext context) {",
  "    return Scaffold(",
  "      appBar: AppBar(title: const Text('Send Inquiry')),",
  "      body: SafeArea(",
  "        child: Padding(",
  "          padding: const EdgeInsets.all(AppTheme.paddingLG),",
  "          child: _sent ? _SuccessView(onDone: () => context.pop()) : _FormView(",
  "            productTitle: widget.productTitle,",
  "            messageCtrl: _messageCtrl,",
  "            sending: _sending,",
  "            error: _error,",
  "            onSend: _sendInquiry,",
  "          ),",
  "        ),",
  "      ),",
  "    );",
  "  }",
  "}",
  "",
  "class _FormView extends StatelessWidget {",
  "  final String? productTitle;",
  "  final TextEditingController messageCtrl;",
  "  final bool sending;",
  "  final String? error;",
  "  final VoidCallback onSend;",
  "",
  "  const _FormView({",
  "    required this.productTitle,",
  "    required this.messageCtrl,",
  "    required this.sending,",
  "    required this.error,",
  "    required this.onSend,",
  "  });",
  "",
  "  @override",
  "  Widget build(BuildContext context) => Column(",
  "        crossAxisAlignment: CrossAxisAlignment.start,",
  "        children: [",
  "          const Icon(Icons.mail_outline, size: 48, color: AppTheme.primary),",
  "          const SizedBox(height: 16),",
  "          Text('Contact the Artisan', style: AppTheme.h2),",
  "          const SizedBox(height: 8),",
  "          if (productTitle != null)",
  "            Text(",
  "              'About: " + S + "productTitle',",
  "              style: AppTheme.bodySmall.copyWith(color: AppTheme.textSecondary),",
  "            ),",
  "          const SizedBox(height: 24),",
  "          Text('Your Message', style: AppTheme.bodySmall.copyWith(fontWeight: FontWeight.w600)),",
  "          const SizedBox(height: 8),",
  "          Expanded(",
  "            child: TextField(",
  "              controller: messageCtrl,",
  "              maxLines: null,",
  "              expands: true,",
  "              textAlignVertical: TextAlignVertical.top,",
  "              decoration: const InputDecoration(",
  "                hintText: 'Hi, I am interested in this product. Could you tell me more about...',",
  "                alignLabelWithHint: true,",
  "              ),",
  "            ),",
  "          ),",
  "          if (error != null) ...[",
  "            const SizedBox(height: 8),",
  "            Text(error!, style: AppTheme.bodySmall.copyWith(color: AppTheme.errorRed)),",
  "          ],",
  "          const SizedBox(height: 16),",
  "          ElevatedButton.icon(",
  "            icon: sending",
  "                ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))",
  "                : const Icon(Icons.send),",
  "            label: Text(sending ? 'Sending...' : 'Send Inquiry'),",
  "            onPressed: sending ? null : onSend,",
  "          ),",
  "        ],",
  "      );",
  "}",
  "",
  "class _SuccessView extends StatelessWidget {",
  "  final VoidCallback onDone;",
  "  const _SuccessView({required this.onDone});",
  "",
  "  @override",
  "  Widget build(BuildContext context) => Center(",
  "        child: Column(",
  "          mainAxisAlignment: MainAxisAlignment.center,",
  "          children: [",
  "            Container(",
  "              width: 80, height: 80,",
  "              decoration: BoxDecoration(",
  "                color: AppTheme.successGreen.withOpacity(0.1),",
  "                shape: BoxShape.circle,",
  "              ),",
  "              child: const Icon(Icons.check_circle_outline, size: 48, color: AppTheme.successGreen),",
  "            ),",
  "            const SizedBox(height: 24),",
  "            Text('Inquiry Sent!', style: AppTheme.h2),",
  "            const SizedBox(height: 8),",
  "            Text(",
  "              'The artisan will receive your message and respond shortly.',",
  "              style: AppTheme.body.copyWith(color: AppTheme.textSecondary),",
  "              textAlign: TextAlign.center,",
  "            ),",
  "            const SizedBox(height: 48),",
  "            ElevatedButton(onPressed: onDone, child: const Text('Back to Product')),",
  "          ],",
  "        ),",
  "      );",
  "}",
].join('\n');

fs.writeFileSync(
  'd:/Hacknex/mobile/lib/features/inquiry/inquiry_screen.dart',
  dart,
  { encoding: 'utf8' }
);
console.log('inquiry_screen.dart written, size:', dart.length);
